### ISSUE TITLE
Examples / Docs outdated?

### ISSUE THREAD

**Issue by Unaidedsteak** [MindFlavor/prometheus_exporter_base#22]
Hey! Apologies if I've missed something, it seems when trying to use the examples or follow the docs, I get the following error:

```  --> src/main.rs:63:5
   |
63 |     render_prometheus(addr, MyOptions::default(), |request, options| async move {
   |     ^^^^^^^^^^^^^^^^^ not found in this scope
```
I'm using the following include:
`use prometheus_exporter_base::prelude::*;`

Any help would be appreciated.

**Comment by Unaidedsteak** [comment]
It seems that the include show now be:
```
use prometheus_exporter_base::*
```

Rather than prelude, does that seem right?

**Comment by araujobsd** [comment]
Yeap, same issue! And that seems right @Unaidedsteak

**Comment by MindFlavor** [comment]
Sorry about that! I'll look into it!

**Comment by MindFlavor** [comment]
Hi guys, your code is right, you just need to import `prelude`.

Also, in order to use the `render_prometheus` function, you **need** to specify the `hyper_server` feature. 
I made it optional because it brings in `hyper` as a reference which is quite big and not needed for the basic Prometheus formatting.

Let me know if we can close this!

**Comment by MindFlavor** [comment]
Closing due to lack of interaction. If it's still broken, please open another issue!
